import type { Provider } from '@playgenx/types';

/**
 * Deterministic provider for tests and offline development.
 *
 * Returns a fixed echo of the prompt wrapped in a stable artifact body so
 * downstream code can be exercised without network calls.
 */
export class MockProvider implements Provider {
  readonly id = 'mock';
  readonly defaultModel = 'mock-1';

  async complete(prompt: string, options?: { model?: string }): Promise<string> {
    return [
      '// Generated by MockProvider',
      `// model: ${options?.model ?? this.defaultModel}`,
      '',
      prompt,
    ].join('\n');
  }
}